interfaces:
 -  name: Gi1
    desc: WAN
    enabled: yes
    ip_address: 172.24.87.11/24
 -  name: Lo0
    desc: Loopback
    enabled: yes
    ip_address: 192.168.11.1/24

bgp:
  as_num: 64011
  router_id: 172.24.87.11
  neighbors:
    - ip: 172.24.87.12
      as: 64012
    - ip: 172.24.87.13
      as: 64013
  networks:
    - prefix: 192.168.11.0
      masklen: 24